/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectcs318;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Punya
 */
public class LevelMenu extends javax.swing.JFrame {
    
    // Data Member
    GlobalVar status ;
    
    // Constructor
    public LevelMenu() {
        // Set Component
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Matching Game Card");
    }
    // Overload
    public LevelMenu(GlobalVar sentPlayer) {
        // Set Component
        this() ;
        status = sentPlayer ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        main_background = new javax.swing.JPanel();
        btn_hard = new javax.swing.JButton();
        btn_easy = new javax.swing.JButton();
        btn_medium = new javax.swing.JButton();
        btn_hard1 = new javax.swing.JButton();
        header2 = new javax.swing.JLabel();

        header.setBackground(new java.awt.Color(204, 204, 255));
        header.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setText("Matching Card Game");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_background.setBackground(new java.awt.Color(181, 212, 238));

        btn_hard.setBackground(new java.awt.Color(134, 175, 207));
        btn_hard.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btn_hard.setForeground(new java.awt.Color(255, 255, 255));
        btn_hard.setText("Hard");
        btn_hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_hardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_hardMouseExited(evt);
            }
        });
        btn_hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hardActionPerformed(evt);
            }
        });

        btn_easy.setBackground(new java.awt.Color(134, 175, 207));
        btn_easy.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btn_easy.setForeground(new java.awt.Color(255, 255, 255));
        btn_easy.setText("Easy");
        btn_easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_easyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_easyMouseExited(evt);
            }
        });
        btn_easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_easyActionPerformed(evt);
            }
        });

        btn_medium.setBackground(new java.awt.Color(134, 175, 207));
        btn_medium.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btn_medium.setForeground(new java.awt.Color(255, 255, 255));
        btn_medium.setText("Medium");
        btn_medium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mediumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mediumMouseExited(evt);
            }
        });
        btn_medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mediumActionPerformed(evt);
            }
        });

        btn_hard1.setBackground(new java.awt.Color(134, 175, 207));
        btn_hard1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btn_hard1.setForeground(new java.awt.Color(255, 255, 255));
        btn_hard1.setText("Back");
        btn_hard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_hard1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_hard1MouseExited(evt);
            }
        });
        btn_hard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hard1ActionPerformed(evt);
            }
        });

        header2.setBackground(new java.awt.Color(0, 0, 0));
        header2.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        header2.setForeground(new java.awt.Color(30, 39, 46));
        header2.setText("Matching Card Game");

        javax.swing.GroupLayout main_backgroundLayout = new javax.swing.GroupLayout(main_background);
        main_background.setLayout(main_backgroundLayout);
        main_backgroundLayout.setHorizontalGroup(
            main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_backgroundLayout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                        .addGroup(main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_easy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_medium, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(btn_hard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_hard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                        .addComponent(header2)
                        .addGap(196, 196, 196))))
        );
        main_backgroundLayout.setVerticalGroup(
            main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_backgroundLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(header2)
                .addGap(48, 48, 48)
                .addComponent(btn_easy, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_medium, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_hard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_hard1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hardActionPerformed
        // Go To Hard Mode
        HardMode hardui = new HardMode(status) ;
        hardui.setVisible(true) ;
        dispose() ;
    }//GEN-LAST:event_btn_hardActionPerformed

    private void btn_easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_easyActionPerformed
        // Go To Easy Mode
        EasyMode easyui = new EasyMode(status) ;
        easyui.setVisible(true) ;
        dispose() ;
    }//GEN-LAST:event_btn_easyActionPerformed

    private void btn_mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mediumActionPerformed
        // Go To Medium Mode
        MediumMode mediumui = new MediumMode(status) ;
        mediumui.setVisible(true) ;
        dispose() ;
    }//GEN-LAST:event_btn_mediumActionPerformed

    private void btn_hard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hard1ActionPerformed
        // Go to Main Menu
        MainMenu ui = new MainMenu(status) ;
        ui.setVisible(true) ;
        dispose() ;
    }//GEN-LAST:event_btn_hard1ActionPerformed

    private void btn_easyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_easyMouseEntered
        // When Enter
        btn_easy.setBackground(new Color(244,249,253)) ;
        btn_easy.setForeground(new Color(51,51,51)) ;
        btn_easy.setBorder(BorderFactory.createLineBorder( new Color(134,175,207),3) );
    }//GEN-LAST:event_btn_easyMouseEntered

    private void btn_easyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_easyMouseExited
        // When Exit
        btn_easy.setBackground(new Color(134,175,207)) ;
        btn_easy.setForeground(new Color(255,255,255)) ;
    }//GEN-LAST:event_btn_easyMouseExited

    private void btn_mediumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mediumMouseEntered
        // When Enter
        btn_medium.setBackground(new Color(244,249,253)) ;
        btn_medium.setForeground(new Color(51,51,51)) ;
        btn_medium.setBorder(BorderFactory.createLineBorder( new Color(134,175,207),3) );
    }//GEN-LAST:event_btn_mediumMouseEntered

    private void btn_mediumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mediumMouseExited
        // When Exit
        btn_medium.setBackground(new Color(134,175,207)) ;
        btn_medium.setForeground(new Color(255,255,255)) ;
    }//GEN-LAST:event_btn_mediumMouseExited

    private void btn_hardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hardMouseEntered
        // When Enter
        btn_hard.setBackground(new Color(244,249,253)) ;
        btn_hard.setForeground(new Color(51,51,51)) ;
        btn_hard.setBorder(BorderFactory.createLineBorder( new Color(134,175,207),3) );
    }//GEN-LAST:event_btn_hardMouseEntered

    private void btn_hardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hardMouseExited
        // When Exit
        btn_hard.setBackground(new Color(134,175,207)) ;
        btn_hard.setForeground(new Color(255,255,255)) ;
    }//GEN-LAST:event_btn_hardMouseExited

    private void btn_hard1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hard1MouseEntered
        // When Enter
        btn_hard1.setBackground(new Color(244,249,253)) ;
        btn_hard1.setForeground(new Color(51,51,51)) ;
        btn_hard1.setBorder(BorderFactory.createLineBorder( new Color(134,175,207),3) );
    }//GEN-LAST:event_btn_hard1MouseEntered

    private void btn_hard1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hard1MouseExited
        // When Exit
        btn_hard1.setBackground(new Color(134,175,207)) ;
        btn_hard1.setForeground(new Color(255,255,255)) ;
    }//GEN-LAST:event_btn_hard1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_easy;
    private javax.swing.JButton btn_hard;
    private javax.swing.JButton btn_hard1;
    private javax.swing.JButton btn_medium;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header2;
    private javax.swing.JPanel main_background;
    // End of variables declaration//GEN-END:variables
}
