/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectcs318;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import javax.swing.BorderFactory;

/**
 *
 * @author Punya
 */
public class MainMenu extends javax.swing.JFrame {
    
    // Data Member
    GlobalVar status ;

    // Constructor
    public MainMenu() {
        // Set Component
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Matching Game Card");
    }
    // OverLoad
    public MainMenu(GlobalVar sentPlayer) {
        // Set Component
        this() ;
        status = sentPlayer ;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        btn_medium = new javax.swing.JButton();
        btn_hard = new javax.swing.JButton();
        main_background = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();
        btn_scoreboard = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel2.setText("Matcing Card Game !");

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel1.setText("Matcing Card Game !");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        label.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        label.setText("Matching Card Game");

        btn_medium.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        btn_medium.setText("Medium");

        btn_hard.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        btn_hard.setText("Easy");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_background.setBackground(new java.awt.Color(181, 212, 238));

        header.setBackground(new java.awt.Color(30, 39, 46));
        header.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        header.setForeground(new java.awt.Color(30, 39, 46));
        header.setText("Matching Card Game");

        btn_exit.setBackground(new java.awt.Color(134, 175, 207));
        btn_exit.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("Save & Exit");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_start.setBackground(new java.awt.Color(134, 175, 207));
        btn_start.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btn_start.setForeground(new java.awt.Color(255, 255, 255));
        btn_start.setText("Start");
        btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_startMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_startMouseExited(evt);
            }
        });
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        btn_scoreboard.setBackground(new java.awt.Color(134, 175, 207));
        btn_scoreboard.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btn_scoreboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_scoreboard.setText("Scoreboard");
        btn_scoreboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_scoreboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_scoreboardMouseExited(evt);
            }
        });
        btn_scoreboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scoreboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_backgroundLayout = new javax.swing.GroupLayout(main_background);
        main_background.setLayout(main_backgroundLayout);
        main_backgroundLayout.setHorizontalGroup(
            main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_backgroundLayout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                        .addGroup(main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_scoreboard, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_start, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                        .addComponent(header)
                        .addGap(197, 197, 197))))
        );
        main_backgroundLayout.setVerticalGroup(
            main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_backgroundLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(header)
                .addGap(65, 65, 65)
                .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btn_scoreboard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        try {
            // Save File
            status.writeFile(status.getEasyScore(),status.getMediumScore(),status.getHardScore()) ;
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose() ;
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        LevelMenu levelselectUI = new LevelMenu(status) ;
        levelselectUI.setVisible(true) ;
        dispose() ;
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_scoreboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scoreboardActionPerformed
        // TODO add your handling code here:
        ScoreboardMenu scoreboardUI = new ScoreboardMenu(status) ;
        scoreboardUI.setVisible(true) ;
        dispose() ;
    }//GEN-LAST:event_btn_scoreboardActionPerformed

    private void btn_startMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_startMouseEntered
        // When Enter
        btn_start.setBackground(new Color(244,249,253)) ;
        btn_start.setForeground(new Color(51,51,51)) ;
        btn_start.setBorder(BorderFactory.createLineBorder( new Color(134,175,207),3) );
    }//GEN-LAST:event_btn_startMouseEntered

    private void btn_startMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_startMouseExited
        // When Exit
        btn_start.setBackground(new Color(134,175,207)) ;
        btn_start.setForeground(new Color(255,255,255)) ;
    }//GEN-LAST:event_btn_startMouseExited

    private void btn_scoreboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_scoreboardMouseEntered
        // When Enter
        btn_scoreboard.setBackground(new Color(244,249,253)) ;
        btn_scoreboard.setForeground(new Color(51,51,51)) ;
        btn_scoreboard.setBorder(BorderFactory.createLineBorder( new Color(134,175,207),3) );
    }//GEN-LAST:event_btn_scoreboardMouseEntered

    private void btn_scoreboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_scoreboardMouseExited
        // When Exit
        btn_scoreboard.setBackground(new Color(134,175,207)) ;
        btn_scoreboard.setForeground(new Color(255,255,255)) ;
    }//GEN-LAST:event_btn_scoreboardMouseExited

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // When Enter
        btn_exit.setBackground(new Color(244,249,253)) ;
        btn_exit.setForeground(new Color(51,51,51)) ;
        btn_exit.setBorder(BorderFactory.createLineBorder( new Color(134,175,207),3) );
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // When Exit
        btn_exit.setBackground(new Color(134,175,207)) ;
        btn_exit.setForeground(new Color(255,255,255)) ;
    }//GEN-LAST:event_btn_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_hard;
    private javax.swing.JButton btn_medium;
    private javax.swing.JButton btn_scoreboard;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label;
    private javax.swing.JPanel main_background;
    // End of variables declaration//GEN-END:variables
}
