/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectcs318;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Punya
 */
public class ResultUI extends javax.swing.JFrame {
    // Data Member
    GlobalVar status ;

    // Constructor
    public ResultUI() {
        // Set Component
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Matching Game Card");
    }
    // Overload
    public ResultUI(GlobalVar sentPlayer,int sentTimer,String sentMode) {
        // Set Component
        this() ;
        status = sentPlayer ;
        // Easy
        if (sentMode.equals("Easy")) {
            currentTime.setText("Times : "+sentTimer+" Second") ;
            // Check Score
            if (sentPlayer.getEasyScore() > sentTimer) {
                sentPlayer.setEasyScore(sentTimer) ;
            }
            playerTime.setText("Player best times : "+sentPlayer.getEasyScore()+" Second") ;
        } else if (sentMode.equals("Medium")) {
            currentTime.setText("Times : "+sentTimer+" Second") ;
            // Check Score
            if (sentPlayer.getMediumScore() > sentTimer) {
                sentPlayer.setMediumScore(sentTimer) ;
            }
            playerTime.setText("Player best times : "+sentPlayer.getMediumScore()+" Second") ;
        } else if (sentMode.equals("Hard")) {
            currentTime.setText("Times : "+sentTimer+" Second") ;
            // Check Score
            if (sentPlayer.getHardScore() > sentTimer) {
                sentPlayer.setHardScore(sentTimer) ;
            }
            playerTime.setText("Player best times : "+sentPlayer.getHardScore()+" Second") ;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_background = new javax.swing.JPanel();
        currentTime = new javax.swing.JLabel();
        playerTime = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        header2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_background.setBackground(new java.awt.Color(181, 212, 238));

        currentTime.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        currentTime.setText("times  : ");

        playerTime.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        playerTime.setText("Player best times : ");

        jButton1.setBackground(new java.awt.Color(134, 175, 207));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back to menu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        header2.setBackground(new java.awt.Color(255, 255, 255));
        header2.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        header2.setForeground(new java.awt.Color(255, 255, 255));
        header2.setText("Result");

        javax.swing.GroupLayout main_backgroundLayout = new javax.swing.GroupLayout(main_background);
        main_background.setLayout(main_backgroundLayout);
        main_backgroundLayout.setHorizontalGroup(
            main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                .addGap(0, 320, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
            .addGroup(main_backgroundLayout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(playerTime, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                        .addComponent(currentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(339, 339, 339))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                        .addComponent(header2)
                        .addGap(378, 378, 378))))
        );
        main_backgroundLayout.setVerticalGroup(
            main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_backgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(header2)
                .addGap(89, 89, 89)
                .addComponent(currentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Go to Main Menu
        MainMenu ui = new MainMenu(status) ;
        ui.setVisible(true) ;
        dispose() ;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // When Enter
        jButton1.setBackground(new Color(244,249,253)) ;
        jButton1.setForeground(new Color(51,51,51)) ;
        jButton1.setBorder(BorderFactory.createLineBorder( new Color(134,175,207),3) );
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // When Exit
        jButton1.setBackground(new Color(134,175,207)) ;
        jButton1.setForeground(new Color(255,255,255)) ;
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentTime;
    private javax.swing.JLabel header2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel main_background;
    private javax.swing.JLabel playerTime;
    // End of variables declaration//GEN-END:variables
}
