/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectcs318;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Punya
 */
public class ScoreboardMenu extends javax.swing.JFrame {

    // Data Member
    GlobalVar status ;
    
    // Constructor
    public ScoreboardMenu() {
        // Set Component
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Matching Game Card");
    }
    // Overload
    public ScoreboardMenu(GlobalVar sentPlayer) {
        // Set Component
        this() ;
        status = sentPlayer ;
        setScoreText() ;
    }

    // Set Text
    private void setScoreText() {
        txt_scoreEasy.setText("Easy Score = "+status.getEasyScore()+" Second" ) ;
        txt_scoreMedium.setText("Medium Score = "+status.getMediumScore()+" Second" ) ;
        txt_scoreHard.setText("Hard Score = "+status.getHardScore()+" Second" ) ;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_background = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        txt_scoreEasy = new javax.swing.JLabel();
        txt_scoreMedium = new javax.swing.JLabel();
        txt_scoreHard = new javax.swing.JLabel();
        header2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(149, 194, 230));

        main_background.setBackground(new java.awt.Color(181, 212, 238));

        btn_exit.setBackground(new java.awt.Color(134, 175, 207));
        btn_exit.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("Back");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        txt_scoreEasy.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        txt_scoreEasy.setText("Easy  : ");

        txt_scoreMedium.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        txt_scoreMedium.setText("Medium : ");

        txt_scoreHard.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        txt_scoreHard.setText("Hard :");

        header2.setBackground(new java.awt.Color(255, 255, 255));
        header2.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        header2.setForeground(new java.awt.Color(30, 39, 46));
        header2.setText("Player Best Score");

        javax.swing.GroupLayout main_backgroundLayout = new javax.swing.GroupLayout(main_background);
        main_background.setLayout(main_backgroundLayout);
        main_backgroundLayout.setHorizontalGroup(
            main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_backgroundLayout.createSequentialGroup()
                .addGap(0, 282, Short.MAX_VALUE)
                .addGroup(main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                        .addGroup(main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_scoreHard, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_scoreMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_scoreEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_backgroundLayout.createSequentialGroup()
                        .addComponent(header2)
                        .addGap(233, 233, 233))))
        );
        main_backgroundLayout.setVerticalGroup(
            main_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_backgroundLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(header2)
                .addGap(70, 70, 70)
                .addComponent(txt_scoreEasy)
                .addGap(37, 37, 37)
                .addComponent(txt_scoreMedium)
                .addGap(36, 36, 36)
                .addComponent(txt_scoreHard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // Main Menu
        MainMenu ui = new MainMenu(status) ;
        ui.setVisible(true) ;
        dispose() ;
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // When Enter
        btn_exit.setBackground(new Color(244,249,253)) ;
        btn_exit.setForeground(new Color(51,51,51)) ;
        btn_exit.setBorder(BorderFactory.createLineBorder( new Color(134,175,207),3) );
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // When Exit
        btn_exit.setBackground(new Color(134,175,207)) ;
        btn_exit.setForeground(new Color(255,255,255)) ;
    }//GEN-LAST:event_btn_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreboardMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel header2;
    private javax.swing.JPanel main_background;
    private javax.swing.JLabel txt_scoreEasy;
    private javax.swing.JLabel txt_scoreHard;
    private javax.swing.JLabel txt_scoreMedium;
    // End of variables declaration//GEN-END:variables
}
